version: "3.2"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/data-persist/nginx/certs:/etc/nginx/certs:ro
      - $PWD/data-persist/nginx/vhost:/etc/nginx/vhost.d
      - $PWD/data-persist/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  portainer:
    image: portainer/portainer
    environment:
      VIRTUAL_HOST: portainer.abibao.com.local.apvo.net
      VIRTUAL_PORT: 9000
    volumes:
      - $PWD/data-persist/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  logstash:
    image: library/logstash:5.6-alpine
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - $PWD/infra/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - $PWD/infra/logstash/pipeline:/usr/share/logstash/pipeline:ro

  couchdb:
    image: library/couchdb:1.6
    environment:
      VIRTUAL_HOST: couchdb.abibao.com.local.apvo.net
      VIRTUAL_PORT: 5984
      COUCHDB_USER: infra
      COUCHDB_PASSWORD: infra

  postgres:
    image: library/postgres:9.6-alpine
    environment:
      POSTGRES_USER: infra
      POSTGRES_PASSWORD: infra

  memcached:
    image: library/memcached:1.5-alpine

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: infra
      RABBITMQ_DEFAULT_PASS: infra

  platform-api:
    image: library/node:8-alpine
    environment:
      VIRTUAL_HOST: api.abibao.com.local.apvo.net
      VIRTUAL_PORT: 3000
    working_dir: /code
    depends_on:
      - rabbitmq
      - postgres
      - logstash
      - couchdb
    volumes:
      - .:/code
    command: "npm run start:server"

  platform-web:
    image: library/node:8-alpine
    environment:
      VIRTUAL_HOST: platform.abibao.com.local.apvo.net
      VIRTUAL_PORT: 4000
    working_dir: /code
    depends_on:
      - rabbitmq
      - postgres
      - logstash
      - couchdb
    volumes:
      - .:/code
    command: "npm start"
