version: "3.2"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  portainer:
    image: portainer/portainer
    environment:
      VIRTUAL_HOST: portainer.abibao.com.local.apvo.net
      VIRTUAL_PORT: 9000
    expose:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  couchdb:
    image: library/couchdb:1.6
    environment:
      VIRTUAL_HOST: couchdb.abibao.com.local.apvo.net
      VIRTUAL_PORT: 5984
      COUCHDB_USER: infra
      COUCHDB_PASSWORD: infra
    expose:
      - 5984

  postgres:
    image: library/postgres:9.6-alpine
    environment:
      POSTGRES_USER: infra
      POSTGRES_PASSWORD: infra
    expose:
      - 5432

  memcached:
    image: library/memcached:1.5-alpine

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    environment:
      VIRTUAL_HOST: rabbitmq.abibao.com.local.apvo.net
      VIRTUAL_PORT: 15672
      RABBITMQ_DEFAULT_USER: infra
      RABBITMQ_DEFAULT_PASS: infra
    expose:
      - 15672
      - 5672

  platform-api:
    image: library/node:8-alpine
    environment:
      VIRTUAL_HOST: api.abibao.com.local.apvo.net
      VIRTUAL_PORT: 3000
    working_dir: /code
    depends_on:
      - rabbitmq
      - postgres
      - couchdb
    expose:
      - 3000
    volumes:
      - .:/code
    command: "tail -F -n0 /etc/hosts"

  platform-dashboard:
    image: library/node:8-alpine
    environment:
      VIRTUAL_HOST: platform.abibao.com.local.apvo.net
      VIRTUAL_PORT: 4000
    working_dir: /code
    expose:
      - 4000
    volumes:
      - .:/code
    command: "node_modules/.bin/static public --host-address 0.0.0.0 -p 4000 --gzip"
