version: '2'

services:

  mysql:
    image: library/postgres:9.6-alpine
    privileged: true
    environment:
      POSTGRES_DB: abibao
      POSTGRES_USER: abibao
      POSTGRES_PASSWORD: abibao
    ports:
      - 5432:5432
